// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.normandy.startupRolloutPrefs.print.tab_modal.enabled", true);
user_pref("app.normandy.user_id", "3352e1b6-f092-40a4-a8e5-09249ce17105");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1615736724);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1615736725);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1615736703);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1615736694);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 104);
user_pref("browser.newtabpage.activity-stream.impressionId", "{07a1818d-4920-44e4-a4c8-a49532506128}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.region.update.updated", 1615736701);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1615736721451");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1615758321451");
user_pref("browser.search.region", "KR");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1615736706");
user_pref("browser.slowStartup.averageTime", 6767);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20210204182252");
user_pref("browser.startup.homepage_override.mstone", "85.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1615736697);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1615736704518");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "85.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("dom.push.userAgentID", "20d15370b7b745a488acb0500598ffeb");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20210204182252");
user_pref("extensions.lastAppVersion", "85.0.1");
user_pref("extensions.lastPlatformVersion", "85.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_picture_in_picture_overrides", true);
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"21237b3d-41e2-45f3-9b77-826417285120\",\"formautofill@mozilla.org\":\"79a05b4d-a0dc-45cc-b253-eced23a99396\",\"screenshots@mozilla.org\":\"1a5a6c40-204b-49e8-a2b0-2d67b282aa34\",\"webcompat-reporter@mozilla.org\":\"346f59c8-a9e1-42e4-a8b1-2f96223962ff\",\"webcompat@mozilla.org\":\"87e5cfde-a070-4f73-a2d1-9501fef2048a\",\"default-theme@mozilla.org\":\"1ab61dab-34ef-4d28-9613-864c005862b9\",\"google@search.mozilla.org\":\"90fcd572-4d8e-432f-ac18-c5ca221289f4\",\"amazondotcom@search.mozilla.org\":\"08527c0a-9c9b-4a6a-8878-a58f486006b8\",\"wikipedia@search.mozilla.org\":\"ccfbb7ea-3733-46a2-84b1-904adc1b1d9b\",\"bing@search.mozilla.org\":\"e4543b60-f6a5-4c66-9be1-762e03962779\",\"ddg@search.mozilla.org\":\"4c206f19-adc1-4585-ae61-303f428e7e58\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "c5fb0b5a-a4f4-46cb-92d5-83e620038e91");
user_pref("security.sandbox.plugin.tempDirSuffix", "dc213ab7-e090-40cf-a555-49f2d7448ac5");
user_pref("toolkit.startup.last_success", 1615736690);
user_pref("toolkit.telemetry.cachedClientID", "33422b80-00fe-489d-8b0e-2d1e6d9bd6bb");
user_pref("toolkit.telemetry.previousBuildID", "20210204182252");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
