// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1615706649);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.cache.disk.amount_written", 876);
user_pref("browser.cache.disk.capacity", 235520);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("calendar.list.sortOrder", "67dda8b3-be29-41f1-97d2-e4d36459f890");
user_pref("calendar.registry.67dda8b3-be29-41f1-97d2-e4d36459f890.calendar-main-in-composite", true);
user_pref("calendar.registry.67dda8b3-be29-41f1-97d2-e4d36459f890.disabled", true);
user_pref("calendar.registry.67dda8b3-be29-41f1-97d2-e4d36459f890.name", "홈");
user_pref("calendar.registry.67dda8b3-be29-41f1-97d2-e4d36459f890.type", "storage");
user_pref("calendar.registry.67dda8b3-be29-41f1-97d2-e4d36459f890.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "Asia/Seoul");
user_pref("calendar.ui.version", 3);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 1);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1615706644251");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "78.7.1");
user_pref("extensions.lastPlatformVersion", "78.7.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"wetransfer@extensions.thunderbird.net\":\"797fb763-ff82-4f73-8d6e-64420b9a3370\",\"default-theme@mozilla.org\":\"36ca431f-77fc-45a9-ae21-ac483a8f390a\",\"google@search.mozilla.org\":\"3fc1aa50-a7bd-4bfd-b47e-c4611fb1bcb5\",\"ddg@search.mozilla.org\":\"09c5ff1a-25e5-4995-9f01-3900e4fcbd6a\",\"naver-kr@search.mozilla.org\":\"5e4bdc07-6d71-4633-8c5b-81cebf5691ca\",\"daum-kr@search.mozilla.org\":\"8d4328ef-85fc-41c0-b9d0-fd0a40603b69\",\"wikipedia@search.mozilla.org\":\"09ed2766-e7e1-48f1-8f5b-912006cc02d6\"}");
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.append_preconfig_smtpservers.version", 2);
user_pref("mail.default_charsets.migrated", 1);
user_pref("mail.folder.views.version", 1);
user_pref("mail.openMessageBehavior.version", 1);
user_pref("mail.spam.version", 1);
user_pref("mail.ui-rdf.version", 23);
user_pref("mailnews.database.global.datastore.id", "cf691a27-4196-4eb1-8537-1b67f0d1827");
user_pref("mailnews.filters.migration78", true);
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "78.7.1");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "중요");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "직장");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "개인");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "할일");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "연기");
user_pref("mailnews.tags.version", 2);
user_pref("places.history.expiration.transient_current_max_pages", 49065);
user_pref("security.sandbox.plugin.tempDirSuffix", "50a1fdc3-9a3d-49d5-b2e1-12bd9870aed6");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.telemetry.cachedClientID", "c9058131-199f-4d96-a8ec-7c38a1e14797");
user_pref("toolkit.telemetry.previousBuildID", "20210203182138");
